apiVersion : apps/v1
kind : Deployment 
metadata : 
   name : wisecow-deployment 
   labels :
      app : wisecow
spec : 
   replicas : 2 
   selector:
      matchLabels:
        app : wisecow
   template :
      metadata :
        labels :
          app : wisecow
      spec :
         containers :
          - name : wisecow 
            image : madhavdhatrak/wisecow:cbbd98f9ea46dd3e2f5234f7a2d276d47e308ecf
            ports :
              - containerPort : 4499
             
