apiVersion : apps/v1
kind : Deployment 
metadata : 
   name : wisecow-deployment 
   labels :
      app : wisecow
spec : 
   replicas : 2 
   selector:
      matchLabels:
        app : wisecow
   template :
      metadata :
        labels :
          app : wisecow
      spec :
         containers :
          - name : wisecow 
            image : madhavdhatrak/wisecow:c77cd3353202a79362bf07101322e88bc7062fcc
            ports :
              - containerPort : 4499
             
